#font_family JetBrainsMono Nerd Font 
font_family Liga SFMono Nerd Font
disable_ligatures never
font_size 14.0
italic_font auto
bold_italic_font auto
bold_font auto 
confirm_os_window_close 0
window_padding_width 8
# Slightly increase line spacing
adjust_line_height 0

#Thicker cursor
#cursor #d2b48c 
#cofee
#cursor #a67b5b 
##orange
#cursor #ff4500
#cursor #ff7f50 
#cursor #a5d8dd
# cursor #2e8b57
cursor_shape block
cursor_blink_interval 0.0
shell_integration no-cursor

#Disable the terminal bell
enable_audio_bell no
scrollback_lines 10000
background_opacity 0.90

#background_image /home/eres/Pictures/wallpaperflare.com_wallpaper(1).jpg
#background_image_layout cscaled
#background_tint 0.95
#repaint_delay 10

# Enable cursor trails (a value > 0 sets the number of fading trail segments)
#cursor_trail 5
cursor_trail                1

# Controls how fast the trail fades out (higher number = faster decay)
cursor_trail_decay 0.1 0.5

# Determines how far the cursor must jump before the trail animation triggers
cursor_trail_start_threshold 2
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

#tab style
tab_bar_edge bottom
tab_bar_style powerline
#tab_bar_style slant


# Tab bar colors
# active_tab_foreground #ffffff
# active_tab_background #333333
# inactive_tab_foreground #888888
# inactive_tab_background #1e1e1e

# Tab title
tab_title_template "{index}:{title}"
active_tab_title_template "{index}:{title}"

# Spacing
tab_bar_margin_width 0
tab_bar_margin_height 0 0

#foreground #F5CCB0
#foreground #d4d3c8
#background_opacity          0.6
#window_padding_width        25
#include themes/noctalia.conf


include themes/noctalia.conf


